
import type { Metadata } from "next"
import "./globals.css"
import Navbar from "../components/NavBar";
import Footer from "../components/Footer";
import Feature from "../components/Feature";
import { CartProvider } from "@/app/context/Cart"
import type React from "react" // Added import for React

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>
        <CartProvider>
          <Navbar />
          {children}
          <Feature />
          <Footer />
        </CartProvider>
      </body>
    </html>
  )
}